#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start VNC Server at boot time.
# Description:       Start VNC Server at boot time.
### END INIT INFO

USER=pi
HOME=/home/pi

export USER HOME

case "$1" in
  start)
    echo "Starting VNC Server"
    su - pi -c "/usr/bin/vncserver :1 -geometry 1024x768 -depth 16 -pixelformat rgb565"
    su - pi -c "/usr/bin/vncserver :2 -geometry 1024x768 -depth 16 -pixelformat rgb565"
    ;;

  stop)
    echo "Stopping VNC Server"
    /usr/bin/vncserver -kill :1
    /usr/bin/vncserver -kill :2
    #/usr/bin/vncserver -kill :3
    #/usr/bin/vncserver -kill :4
    #/usr/bin/vncserver -kill :5
    ;;

  *)
    echo "Usage: /etc/init.d/vncserver {start|stop}"
    exit 1
    ;;
esac

exit 0
